name: Publish performance benchmarks

on:
  workflow_run:
    workflows: 'Performance benchmarks'
    types: 
      - completed

jobs:
  comment_pr:
    permissions:
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v8
        with:
          name: benchmarks
          path: ./benchmarks
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
